[[getting]]
= Spring Security 가져오기

이 섹션에서는 Spring Security 바이너리를 가져오는 방법을 설명합니다.
소스 코드를 얻는 방법은 xref:community.adoc#community-source[소스 코드]를 참조하세요.

== 릴리스 번호 체계

Spring Security 버전은 MAJOR.MINOR.PATCH 형식으로 되어 있으며:

* MAJOR 버전은 호환성이 깨지는 변경사항을 포함할 수 있습니다.
일반적으로 이는 현대적인 보안 관행에 맞춰 개선된 보안을 제공하기 위해 수행됩니다.
* MINOR 버전은 기능 개선을 포함하지만 수동적 업데이트로 간주됩니다.
* PATCH 레벨은 버그 수정을 제외하고는 이전 버전과 이후 버전 모두와 호환성이 완벽해야 합니다.

[[maven]]
== Maven과 함께 사용하기

대부분의 오픈 소스 프로젝트와 마찬가지로 Spring Security는 의존성을 Maven 아티팩트로 배포합니다.
이 섹션의 주제들은 Maven을 사용할 때 Spring Security를 사용하는 방법을 설명합니다.

[[getting-maven-boot]]
=== Maven과 함께 Spring Boot 사용하기

Spring Boot는 Spring Security 관련 의존성을 모아놓은 `spring-boot-starter-security` 스타터를 제공합니다.
스타터를 사용하는 가장 간단하고 선호되는 방법은 IDE 통합 (https://joshlong.com/jl/blogPost/tech_tip_geting_started_with_spring_boot.html[Eclipse] 또는 https://www.jetbrains.com/help/idea/spring-boot.html#d1489567e2[IntelliJ], https://github.com/AlexFalappa/nb-springboot/wiki/Quick-Tour[NetBeans])을 통해 또는 https://start.spring.io를 통해 https://docs.spring.io/initializr/docs/current/reference/html/[Spring Initializr]를 사용하는 것입니다.
또는 다음 예시와 같이 수동으로 스타터를 추가할 수 있습니다:

.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... 다른 의존성 요소들 ... -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-security</artifactId>
	</dependency>
</dependencies>
----

Spring Boot는 의존성 버전을 관리하기 위해 Maven BOM(Bill of Materials)을 제공하므로 버전을 지정할 필요가 없습니다.
Spring Security 버전을 재정의하려면 Maven 속성을 제공하여 수행할 수 있습니다:

.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring-security.version>{spring-security-version}</spring-security.version>
</properties>
----

Spring Security는 주요 릴리스에서만 호환성이 깨지는 변경을 하므로 Spring Boot와 함께 더 새로운 버전의 Spring Security를 안전하게 사용할 수 있습니다.
그러나 때로는 Spring Framework의 버전도 업데이트해야 할 수 있습니다.
다음과 같이 Maven 속성을 추가하여 이를 수행할 수 있습니다:

.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring.version>{spring-core-version}</spring.version>
</properties>
----

추가 기능(LDAP, OAuth 2 등)을 사용하는 경우 적절한 xref:modules.adoc#modules[프로젝트 모듈 및 의존성]도 포함해야 합니다.

[[getting-maven-no-boot]]
=== Spring Boot 없이 Maven 사용하기

Spring Boot 없이 Spring Security를 사용할 때는 전체 프로젝트에서 일관된 버전의 Spring Security를 사용하도록 하기 위해 Spring Security의 BOM을 사용하는 것이 선호됩니다. 다음 예시는 이를 수행하는 방법을 보여줍니다:

.pom.xml
[source,xml,ubs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... 다른 의존성 요소들 ... -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-bom</artifactId>
			<version>{spring-security-version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
----

최소한의 Spring Security Maven 의존성 세트는 일반적으로 다음 예시와 같습니다:

.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... 다른 의존성 요소들 ... -->
	<dependency>
		<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-web</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-config</artifactId>
	</dependency>
</dependencies>
----

추가 기능(LDAP, OAuth 2 등)을 사용하는 경우 적절한 xref:modules.adoc#modules[프로젝트 모듈 및 의존성]도 포함해야 합니다.

Spring Security는 Spring Framework {spring-core-version}에 대해 빌드되지만 일반적으로 Spring Framework 5.x의 더 새로운 버전과 함께 작동해야 합니다.
많은 사용자들이 Spring Security의 전이적 의존성이 Spring Framework {spring-core-version}을 해결하여 이상한 클래스패스 문제를 일으킬 수 있다는 사실을 간과하기 쉽습니다.
이를 해결하는 가장 쉬운 방법은 ``pom.xml``의 `<dependencyManagement>` 섹션 내에 ``spring-framework-bom``을 사용하는 것입니다:

.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... 다른 의존성 요소들 ... -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-framework-bom</artifactId>
			<version>{spring-core-version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
----

위의 예시는 Spring Security의 모든 전이적 의존성이 Spring {spring-core-version} 모듈을 사용하도록 보장합니다.

[NOTE]
====
이 접근 방식은 Maven의 "자재 명세서" (BOM) 개념을 사용하며 Maven 2.0.9+ 에서만 사용 가능합니다.
의존성 해결 방식에 대한 추가 세부 정보는 https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven의 의존성 메커니즘 소개 문서]를 참조하세요.
====

[[maven-repositories]]
=== Maven 저장소
모든 GA 릴리스(즉, .RELEASE로 끝나는 버전)는 Maven Central에 배포되므로 pom에 추가 Maven 저장소를 선언할 필요가 없습니다.

SNAPSHOT 버전을 사용하는 경우 Spring Snapshot 저장소가 정의되어 있는지 확인해야 합니다:

.pom.xml
[source,xml]
----
<repositories>
	<!-- ... 다른 저장소 요소들이 있을 수 있음 ... -->
	<repository>
		<id>spring-snapshot</id>
		<name>Spring Snapshot Repository</name>
		<url>https://repo.spring.io/snapshot</url>
	</repository>
</repositories>
----

마일스톤이나 릴리스 후보 버전을 사용하는 경우 다음 예시와 같이 Spring Milestone 저장소가 정의되어 있는지 확인해야 합니다:

.pom.xml
[source,xml]
----
<repositories>
	<!-- ... 다른 저장소 요소들이 있을 수 있음 ... -->
	<repository>
		<id>spring-milestone</id>
		<name>Spring Milestone Repository</name>
		<url>https://repo.spring.io/milestone</url>
	</repository>
</repositories>
----

[[getting-gradle]]
== Gradle

대부분의 오픈 소스 프로젝트와 마찬가지로 Spring Security는 의존성을 Maven 아티팩트로 배포하여 Gradle에 대한 완전한 지원을 가능하게 합니다.
다음 주제들은 Gradle을 사용할 때 Spring Security를 사용하는 방법을 설명합니다.

[[getting-gradle-boot]]
=== Gradle과 함께 Spring Boot 사용하기

Spring Boot는 Spring Security 관련 의존성을 모아놓은 `spring-boot-starter-security` 스타터를 제공합니다.
스타터를 사용하는 가장 간단하고 선호되는 방법은 IDE 통합 (https://joshlong.com/jl/blogPost/tech_tip_geting_started_with_spring_boot.html[Eclipse] 또는 https://www.jetbrains.com/help/idea/spring-boot.html#d1489567e2[IntelliJ], https://github.com/AlexFalappa/nb-springboot/wiki/Quick-Tour[NetBeans])을 통해 또는 link:[https://start.spring.io]를 통해 https://docs.spring.io/initializr/docs/current/reference/html/[Spring Initializr]를 사용하는 것입니다.

또는 수동으로 스타터를 추가할 수 있습니다:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	implementation "org.springframework.boot:spring-boot-starter-security"
}
----

Spring Boot는 의존성 버전을 관리하기 위해 Maven BOM을 제공하므로 버전을 지정할 필요가 없습니다.
Spring Security 버전을 재정의하려면 Gradle 속성을 제공하여 수행할 수 있습니다:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring-security.version']='{spring-security-version}'
----

Spring Security는 주요 릴리스에서만 호환성이 깨지는 변경을 하므로 Spring Boot와 함께 더 새로운 버전의 Spring Security를 안전하게 사용할 수 있습니다.
그러나 때로는 Spring Framework의 버전도 업데이트해야 할 수 있습니다.
다음과 같이 Gradle 속성을 추가하여 이를 수행할 수 있습니다:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring.version']='{spring-core-version}'
----

추가 기능(LDAP, OAuth 2 등)을 사용하는 경우 적절한 xref:modules.adoc#modules[프로젝트 모듈 및 의존성]도 포함해야 합니다.

=== Spring Boot 없이 Gradle 사용하기

Spring Boot 없이 Spring Security를 사용할 때는 전체 프로젝트에서 일관된 버전의 Spring Security를 사용하도록 하기 위해 Spring Security의 BOM을 사용하는 것이 선호됩니다.
https://github.com/spring-gradle-plugins/dependency-management-plugin[Dependency Management Plugin]을 사용하여 이를 수행할 수 있습니다:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.security:spring-security-bom:{spring-security-version}'
	}
}
----

최소한의 Spring Security Maven 의존성 세트는 일반적으로 다음과 같습니다:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	implementation "org.springframework.security:spring-security-web"
	implementation "org.springframework.security:spring-security-config"
}
----

추가 기능(LDAP, OAuth 2 등)을 사용하는 경우 적절한 xref:modules.adoc#modules[프로젝트 모듈 및 의존성]도 포함해야 합니다.

Spring Security는 Spring Framework {spring-core-version}에 대해 빌드되지만 일반적으로 Spring Framework 5.x의 더 새로운 버전과 함께 작동해야 합니다.
많은 사용자들이 Spring Security의 전이적 의존성이 Spring Framework {spring-core-version}을 해결하여 이상한 클래스패스 문제를 일으킬 수 있다는 사실을 간과하기 쉽습니다.
이를 해결하는 가장 쉬운 방법은 ``build.gradle``의 `dependencyManagement` 섹션 내에 ``spring-framework-bom``을 사용하는 것입니다.
https://github.com/spring-gradle-plugins/dependency-management-plugin[Dependency Management Plugin]을 사용하여 이를 수행할 수 있습니다:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework:spring-framework-bom:{spring-core-version}'
	}
}
----

위의 예시는 Spring Security의 모든 전이적 의존성이 Spring {spring-core-version} 모듈을 사용하도록 보장합니다.

[[gradle-repositories]]
=== Gradle 저장소
모든 GA 릴리스(즉, .RELEASE로 끝나는 버전)는 Maven Central에 배포되므로 GA 릴리스의 경우 `mavenCentral()` 저장소를 사용하는 것으로 충분합니다. 다음 예시는 이를 수행하는 방법을 보여줍니다:

.build.gradle
[source,groovy]
----
repositories {
	mavenCentral()
}
----

SNAPSHOT 버전을 사용하는 경우 Spring Snapshot 저장소가 정의되어 있는지 확인해야 합니다:

.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/snapshot' }
}
----

마일스톤이나 릴리스 후보 버전을 사용하는 경우 Spring Milestone 저장소가 정의되어 있는지 확인해야 합니다:

.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/milestone' }
}
----