[[servlet-jaas]]
= Java 인증 및 인가 서비스(JAAS) 제공자

Spring Security는 인증 요청을 Java 인증 및 인가 서비스(JAAS)에 위임하기 위한 패키지를 제공합니다.
이 섹션에서는 해당 패키지에 대해 설명합니다.

[[jaas-abstractjaasauthenticationprovider]]
== AbstractJaasAuthenticationProvider
`AbstractJaasAuthenticationProvider` 클래스는 제공된 JAAS `AuthenticationProvider` 구현의 기초입니다.
하위 클래스는 ``LoginContext``를 생성하는 메서드를 구현해야 합니다.
``AbstractJaasAuthenticationProvider``는 이 섹션의 나머지 부분에서 설명하는 여러 의존성을 주입할 수 있습니다.

[[jaas-callbackhandler]]
=== JAAS CallbackHandler
대부분의 JAAS `LoginModule` 인스턴스는 어떤 형태의 콜백을 필요로 합니다.
이러한 콜백은 주로 사용자로부터 사용자 이름과 비밀번호를 얻는 데 사용됩니다.

Spring Security 배포에서는 Spring Security가 이러한 사용자 상호작용을 담당합니다(인증 메커니즘을 통해).
따라서 인증 요청이 JAAS로 위임되는 시점에는 Spring Security의 인증 메커니즘이 이미 JAAS ``LoginModule``에 필요한 모든 정보를 포함하는 `Authentication` 객체를 완전히 채웠습니다.

따라서 Spring Security용 JAAS 패키지는 두 가지 기본 콜백 핸들러를 제공합니다: ``JaasNameCallbackHandler``와 ``JaasPasswordCallbackHandler``입니다.
이 콜백 핸들러들은 각각 ``JaasAuthenticationCallbackHandler``를 구현합니다.
대부분의 경우 내부 메커니즘을 이해하지 않고도 이러한 콜백 핸들러를 사용할 수 있습니다.

콜백 동작을 완전히 제어해야 하는 경우, ``AbstractJaasAuthenticationProvider``는 내부적으로 이러한 ``JaasAuthenticationCallbackHandler`` 인스턴스를 ``InternalCallbackHandler``로 래핑합니다.
``InternalCallbackHandler``는 실제로 JAAS의 일반적인 `CallbackHandler` 인터페이스를 구현하는 클래스입니다.
JAAS ``LoginModule``이 사용될 때마다 구성된 애플리케이션 컨텍스트의 ``InternalCallbackHandler`` 인스턴스 목록이 전달됩니다.
``LoginModule``이 ``InternalCallbackHandler`` 인스턴스에 대해 콜백을 요청하면, 그 콜백은 차례로 래핑된 ``JaasAuthenticationCallbackHandler`` 인스턴스로 전달됩니다.

[[jaas-authoritygranter]]
=== JAAS AuthorityGranter
JAAS는 주체(principal)와 함께 작동합니다.
JAAS에서는 "역할"조차도 주체로 표현됩니다.
반면 Spring Security는 `Authentication` 객체와 함께 작동합니다.
각 `Authentication` 객체는 단일 주체와 여러 `GrantedAuthority` 인스턴스를 포함합니다.
이러한 서로 다른 개념 간의 매핑을 용이하게 하기 위해 Spring Security의 JAAS 패키지는 `AuthorityGranter` 인터페이스를 포함합니다.

``AuthorityGranter``는 JAAS 주체를 검사하고 해당 주체에 할당된 권한을 나타내는 `String` 객체 집합을 반환합니다.
반환된 각 권한 문자열에 대해 ``AbstractJaasAuthenticationProvider``는 권한 문자열과 ``AuthorityGranter``에 전달된 JAAS 주체를 포함하는 ``JaasGrantedAuthority``(Spring Security의 `GrantedAuthority` 인터페이스를 구현)를 생성합니다.
``AbstractJaasAuthenticationProvider``는 먼저 JAAS ``LoginModule``을 사용하여 사용자의 자격 증명을 성공적으로 인증한 다음 반환된 ``LoginContext``에 접근하여 JAAS 주체를 얻습니다.
`LoginContext.getSubject().getPrincipals()` 호출이 이루어지며, 결과로 나온 각 주체는 `AbstractJaasAuthenticationProvider.setAuthorityGranters(List)` 속성에 정의된 각 ``AuthorityGranter``에 전달됩니다.

모든 JAAS 주체가 구현별로 특정한 의미를 가지기 때문에 Spring Security는 프로덕션 `AuthorityGranter` 인스턴스를 포함하지 않습니다.
그러나 단위 테스트에 간단한 `AuthorityGranter` 구현을 보여주는 ``TestAuthorityGranter``가 있습니다.

[[jaas-defaultjaasauthenticationprovider]]
== DefaultJaasAuthenticationProvider
``DefaultJaasAuthenticationProvider``는 JAAS ``Configuration`` 객체를 의존성으로 주입할 수 있게 합니다.
그런 다음 주입된 JAAS ``Configuration``을 사용하여 ``LoginContext``를 생성합니다.
이는 ``DefaultJaasAuthenticationProvider``가 ``JaasAuthenticationProvider``와 달리 특정 `Configuration` 구현에 묶이지 않음을 의미합니다.

[[jaas-inmemoryconfiguration]]
=== InMemoryConfiguration
``DefaultJaasAuthenticationProvider``에 ``Configuration``을 쉽게 주입할 수 있도록 ``InMemoryConfiguration``이라는 기본 인메모리 구현이 제공됩니다.
이 구현의 생성자는 각 키가 로그인 구성 이름을 나타내고 값이 `AppConfigurationEntry` 인스턴스의 ``Array``를 나타내는 ``Map``을 받습니다.
``InMemoryConfiguration``은 또한 제공된 ``Map``에서 매핑을 찾을 수 없을 때 사용되는 기본 `AppConfigurationEntry` 객체의 ``Array``를 지원합니다.
자세한 내용은 {security-api-url}org/springframework/security/authentication/jaas/memory/InMemoryConfiguration.html[``InMemoryConfiguration``의 Javadoc]을 참조하세요.

[[jaas-djap-config]]
=== DefaultJaasAuthenticationProvider 예제 구성
``InMemoryConfiguration``에 대한 Spring 구성이 표준 JAAS 구성 파일보다 더 장황할 수 있지만, ``DefaultJaasAuthenticationProvider``와 함께 사용하면 기본 ``Configuration`` 구현에 의존하지 않기 때문에 `JaasAuthenticationProvider`보다 더 유연합니다.

다음 예제는 ``InMemoryConfiguration``을 사용하는 ``DefaultJaasAuthenticationProvider``의 구성을 제공합니다.
사용자 정의 ``Configuration`` 구현도 쉽게 ``DefaultJaasAuthenticationProvider``에 주입할 수 있습니다.

[source,xml]
----
<bean id="jaasAuthProvider"
class="org.springframework.security.authentication.jaas.DefaultJaasAuthenticationProvider">
<property name="configuration">
<bean class="org.springframework.security.authentication.jaas.memory.InMemoryConfiguration">
<constructor-arg>
	<map>
	<!--
	SPRINGSECURITY는 AbstractJaasAuthenticationProvider의
	기본 loginContextName입니다
	-->
	<entry key="SPRINGSECURITY">
	<array>
	<bean class="javax.security.auth.login.AppConfigurationEntry">
		<constructor-arg value="sample.SampleLoginModule" />
		<constructor-arg>
		<util:constant static-field=
			"javax.security.auth.login.AppConfigurationEntry$LoginModuleControlFlag.REQUIRED"/>
		</constructor-arg>
		<constructor-arg>
		<map></map>
		</constructor-arg>
		</bean>
	</array>
	</entry>
	</map>
	</constructor-arg>
</bean>
</property>
<property name="authorityGranters">
<list>
	<!-- AuthorityGranter의 자체 구현을 작성해야 합니다 -->
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
</list>
</property>
</bean>
----

[[jaas-jaasauthenticationprovider]]
== JaasAuthenticationProvider
``JaasAuthenticationProvider``는 기본 ``Configuration``이 https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/login/ConfigFile.html[`ConfigFile`]의 인스턴스라고 가정합니다.
이 가정은 ``Configuration``을 업데이트하려고 시도하기 위해 이루어집니다.
그런 다음 ``JaasAuthenticationProvider``는 기본 ``Configuration``을 사용하여 ``LoginContext``를 생성합니다.

다음과 같은 내용의 JAAS 로그인 구성 파일 ``/WEB-INF/login.conf``가 있다고 가정해봅시다:

[source,txt]
----
JAASTest {
	sample.SampleLoginModule required;
};
----

모든 Spring Security 빈과 마찬가지로 ``JaasAuthenticationProvider``는 애플리케이션 컨텍스트를 통해 구성됩니다.
다음 정의는 위의 JAAS 로그인 구성 파일에 해당합니다:

[source,xml]
----

<bean id="jaasAuthenticationProvider"
class="org.springframework.security.authentication.jaas.JaasAuthenticationProvider">
<property name="loginConfig" value="/WEB-INF/login.conf"/>
<property name="loginContextName" value="JAASTest"/>
<property name="callbackHandlers">
<list>
<bean
	class="org.springframework.security.authentication.jaas.JaasNameCallbackHandler"/>
<bean
	class="org.springframework.security.authentication.jaas.JaasPasswordCallbackHandler"/>
</list>
</property>
<property name="authorityGranters">
	<list>
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
	</list>
</property>
</bean>
----

[[jaas-apiprovision]]
== Subject로 실행하기
구성된 경우, ``JaasApiIntegrationFilter``는 ``JaasAuthenticationToken``의 ``Subject``로 실행을 시도합니다.
이는 ``Subject``에 다음과 같이 접근할 수 있음을 의미합니다:

[source,java]
----
Subject subject = Subject.getSubject(AccessController.getContext());
----

xref:servlet/appendix/namespace/http.adoc#nsa-http-jaas-api-provision[jaas-api-provision] 속성을 사용하여 이 통합을 구성할 수 있습니다.
이 기능은 JAAS Subject가 채워져 있어야 하는 레거시 또는 외부 API와 통합할 때 유용합니다.