[[runas]]
= Run-As 인증 대체

[[runas-overview]]
``AbstractSecurityInterceptor``는 보안 객체 콜백 단계 동안 ``SecurityContext``와 ``SecurityContextHolder``의 ``Authentication`` 객체를 일시적으로 대체할 수 있습니다.
이는 원래의 `Authentication` 객체가 ``AuthenticationManager``와 ``AccessDecisionManager``에 의해 성공적으로 처리된 경우에만 발생합니다.
``RunAsManager``는 ``SecurityInterceptorCallback`` 동안 사용해야 할 대체 ``Authentication`` 객체(있는 경우)를 지정합니다.

보안 객체 콜백 단계에서 ``Authentication`` 객체를 일시적으로 대체함으로써, 보안 호출은 다른 인증 및 권한 부여 자격 증명이 필요한 다른 객체를 호출할 수 있습니다.
또한 특정 ``GrantedAuthority`` 객체에 대한 내부 보안 검사를 수행할 수 있습니다.
Spring Security는 ``SecurityContextHolder``의 내용을 기반으로 원격 프로토콜을 자동으로 구성하는 여러 헬퍼 클래스를 제공하므로, 이러한 run-as 대체는 원격 웹 서비스를 호출할 때 특히 유용합니다.

[[runas-config]]
== 구성
Spring Security는 ``RunAsManager`` 인터페이스를 제공합니다:

[source,java]
----
Authentication buildRunAs(Authentication authentication, Object object,
	List<ConfigAttribute> config);

boolean supports(ConfigAttribute attribute);

boolean supports(Class clazz);
----

첫 번째 메소드는 메소드 호출 기간 동안 기존 ``Authentication`` 객체를 대체해야 하는 ``Authentication`` 객체를 반환합니다.
이 메소드가 ``null``을 반환하면 대체가 필요하지 않음을 나타냅니다.
두 번째 메소드는 ``AbstractSecurityInterceptor``가 구성 속성의 시작 유효성 검사의 일부로 사용합니다.
`supports(Class)` 메소드는 보안 인터셉터 구현에 의해 호출되어 구성된 ``RunAsManager``가 보안 인터셉터가 제시하는 보안 객체 유형을 지원하는지 확인합니다.

Spring Security는 ``RunAsManager``의 구체적인 구현을 하나 제공합니다.
``RunAsManagerImpl`` 클래스는 ``RUN_AS_``로 시작하는 ``ConfigAttribute``가 있는 경우 대체 ``RunAsUserToken``을 반환합니다.
그러한 ``ConfigAttribute``가 발견되면, 대체 ``RunAsUserToken``은 원래 ``Authentication`` 객체와 동일한 주체, 자격 증명, 부여된 권한과 함께 각 ``RUN_AS_`` ``ConfigAttribute``에 대한 새로운 `SimpleGrantedAuthority`를 포함합니다.
각 새로운 ``SimpleGrantedAuthority``는 ``ROLE_``로 시작하고, 그 뒤에 ``RUN_AS`` ``ConfigAttribute``가 붙습니다.
예를 들어, ``RUN_AS_SERVER``는 대체 ``RunAsUserToken``에 ``ROLE_RUN_AS_SERVER`` 부여 권한을 포함하게 합니다.

대체 ``RunAsUserToken``은 다른 ``Authentication`` 객체와 마찬가지입니다.
적절한 ``AuthenticationProvider``에 위임하여 ``AuthenticationManager``에 의해 인증되어야 합니다.
``RunAsImplAuthenticationProvider``가 이러한 인증을 수행합니다.
이는 제시된 모든 ``RunAsUserToken``을 유효한 것으로 받아들입니다.

악의적인 코드가 ``RunAsUserToken``을 생성하여 ``RunAsImplAuthenticationProvider``에 의해 보장된 수락을 위해 제시하는 것을 방지하기 위해, 키의 해시가 생성된 모든 토큰에 저장됩니다.
``RunAsManagerImpl``과 ``RunAsImplAuthenticationProvider``는 빈 컨텍스트에서 동일한 키로 생성됩니다:

[source,xml]
----
<bean id="runAsManager"
	class="org.springframework.security.access.intercept.RunAsManagerImpl">
<property name="key" value="my_run_as_password"/>
</bean>

<bean id="runAsAuthenticationProvider"
	class="org.springframework.security.access.intercept.RunAsImplAuthenticationProvider">
<property name="key" value="my_run_as_password"/>
</bean>
----

동일한 키를 사용함으로써, 각 ``RunAsUserToken``은 승인된 ``RunAsManagerImpl``에 의해 생성되었기 때문에 검증될 수 있습니다.
``RunAsUserToken``은 보안상의 이유로 생성 후 변경할 수 없습니다.