[[servlet-x509]]
= X.509 인증

[[x509-overview]]
X.509 인증서 인증의 가장 일반적인 용도는 SSL을 사용할 때 서버의 신원을 확인하는 것입니다. 주로 브라우저에서 HTTPS를 사용할 때 볼 수 있습니다.
브라우저는 서버가 제시한 인증서가 자체적으로 유지하는 신뢰할 수 있는 인증 기관 목록 중 하나에 의해 발급(디지털 서명)되었는지 자동으로 확인합니다.

"상호 인증"을 사용하여 SSL을 활용할 수도 있습니다. 이 경우 서버는 SSL 핸드셰이크의 일부로 클라이언트에게 유효한 인증서를 요청합니다.
서버는 클라이언트의 인증서가 허용 가능한 기관에 의해 서명되었는지 확인하여 클라이언트를 인증합니다.
유효한 인증서가 제공된 경우, 애플리케이션에서 서블릿 API를 통해 이를 얻을 수 있습니다.
Spring Security X.509 모듈은 필터를 사용하여 인증서를 추출합니다.
이 모듈은 인증서를 애플리케이션 사용자에게 매핑하고, 해당 사용자의 권한 집합을 로드하여 표준 Spring Security 인프라와 함께 사용합니다.

"상호 인증"을 사용하여 SSL을 활용할 수도 있습니다. 이 경우 서버는 SSL 핸드셰이크의 일부로 클라이언트에게 유효한 인증서를 요청합니다.
서버는 클라이언트의 인증서가 허용 가능한 기관에 의해 서명되었는지 확인하여 클라이언트를 인증합니다.
예를 들어, Tomcat을 사용하는 경우 https://tomcat.apache.org/tomcat-10.1-doc/ssl-howto.html[Tomcat SSL 설명서]를 참조해야 합니다.
Spring Security와 함께 사용하기 전에 이 설정을 먼저 완료해야 합니다.

== 웹 애플리케이션에 X.509 인증 추가하기
X.509 클라이언트 인증을 활성화하는 것은 매우 간단합니다.
이를 위해 http 보안 네임스페이스 구성에 `<x509/>` 요소를 추가하세요:

[source,xml]
----
<http>
...
	<x509 subject-principal-regex="CN=(.*?)," user-service-ref="userService"/>;
</http>
----

이 요소에는 두 가지 선택적 속성이 있습니다:

* ``subject-principal-regex``.
인증서의 주체 이름에서 사용자 이름을 추출하는 데 사용되는 정규 표현식입니다.
기본값은 위의 예시와 같습니다.
이는 사용자의 권한을 로드하기 위해 ``UserDetailsService``에 전달되는 사용자 이름입니다.
* ``user-service-ref``.
X.509와 함께 사용될 ``UserDetailsService``의 빈 ID입니다.
애플리케이션 컨텍스트에 하나만 정의되어 있다면 필요하지 않습니다.

``subject-principal-regex``는 단일 그룹을 포함해야 합니다.
예를 들어, 기본 표현식(`CN=(.*?)`)은 공통 이름 필드와 일치합니다.
따라서 인증서의 주체 이름이 "CN=Jimi Hendrix, OU=..."인 경우, 사용자 이름은 "Jimi Hendrix"가 됩니다.
일치는 대소문자를 구분하지 않습니다.
따라서 "emailAddress=(+.*?+),"는 "EMAILADDRESS=jimi@hendrix.org,CN=..."와 일치하여 사용자 이름 "jimi@hendrix.org"를 제공합니다.
클라이언트가 인증서를 제시하고 유효한 사용자 이름이 성공적으로 추출되면, 보안 컨텍스트에 유효한 `Authentication` 객체가 있어야 합니다.
인증서를 찾을 수 없거나 해당하는 사용자를 찾을 수 없는 경우 보안 컨텍스트는 비어 있습니다.
이는 X.509 인증을 폼 기반 로그인과 같은 다른 옵션과 함께 사용할 수 있음을 의미합니다.

[[x509-ssl-config]]
== Tomcat에서 SSL 설정하기
Spring Security Samples 저장소의 {gh-samples-url}/servlet/java-configuration/authentication/x509/server[이 위치]에 미리 생성된 인증서가 있습니다.
자체 인증서를 생성하고 싶지 않다면 테스트를 위해 SSL을 활성화하는 데 이를 사용할 수 있습니다.
``server.jks`` 파일에는 서버 인증서, 개인 키, 발급 기관 인증서가 포함되어 있습니다.
또한 샘플 애플리케이션의 사용자를 위한 클라이언트 인증서 파일도 있습니다.
이를 브라우저에 설치하여 SSL 클라이언트 인증을 활성화할 수 있습니다.

SSL 지원으로 Tomcat을 실행하려면 `server.jks` 파일을 Tomcat의 `conf` 디렉토리에 넣고 `server.xml` 파일에 다음 커넥터를 추가하세요:

[source,xml]
----
<Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true" scheme="https" secure="true"
			clientAuth="true" sslProtocol="TLS"
			keystoreFile="${catalina.home}/conf/server.jks"
			keystoreType="JKS" keystorePass="password"
			truststoreFile="${catalina.home}/conf/server.jks"
			truststoreType="JKS" truststorePass="password"
/>
----

클라이언트가 인증서를 제공하지 않더라도 SSL 연결이 성공하기를 원한다면 ``clientAuth``를 ``want``로 설정할 수도 있습니다.
인증서를 제시하지 않는 클라이언트는 폼 인증과 같은 X.509가 아닌 인증 메커니즘을 사용하지 않는 한 Spring Security로 보호된 객체에 접근할 수 없습니다.