[[servlet-authentication-digest]]
= 다이제스트 인증

이 섹션에서는 Spring Security가 ``DigestAuthenticationFilter``를 통해 제공하는 다이제스트 인증 지원에 대해 자세히 설명합니다.

[WARNING]
====
현대 애플리케이션에서는 다이제스트 인증을 사용하지 않는 것이 좋습니다. 이는 안전하지 않은 것으로 간주되기 때문입니다.
가장 명백한 문제는 비밀번호를 일반 텍스트나 암호화된 형태 또는 MD5 형식으로 저장해야 한다는 점입니다.
이러한 모든 저장 형식은 안전하지 않은 것으로 간주됩니다.
대신, 단방향 적응형 비밀번호 해시(bCrypt, PBKDF2, SCrypt 등)를 사용하여 자격 증명을 저장해야 합니다. 이는 다이제스트 인증에서 지원되지 않습니다.
====

다이제스트 인증은 기본 인증의 여러 약점을 해결하려고 시도합니다. 특히 자격 증명이 네트워크를 통해 일반 텍스트로 전송되지 않도록 합니다.
많은 브라우저가 다이제스트 인증을 지원합니다.

HTTP 다이제스트 인증을 관리하는 표준은 RFC 2617에 의해 정의되었으며, 이는 RFC 2069에서 규정한 이전 버전의 다이제스트 인증 표준을 업데이트한 것입니다.
대부분의 사용자 에이전트는 RFC 2617을 구현합니다.
Spring Security의 다이제스트 인증 지원은 RFC 2617에서 규정한 "auth" 품질의 보호(``qop - Quality of Protection``)와 호환되며, RFC 2069와의 하위 호환성도 제공합니다.
다이제스트 인증은 암호화되지 않은 HTTP(TLS 또는 HTTPS 없음)를 사용해야 하고 인증 과정의 보안을 최대화하고자 할 때 더 매력적인 옵션으로 여겨졌습니다.
하지만 모든 사람이 HTTPS를 사용해야 합니다.

다이제스트 인증의 핵심은 "nonce"입니다. 이는 서버가 생성하는 값입니다.
Spring Security의 nonce는 다음과 같은 형식을 채택합니다:

.다이제스트 구문
[source,txt]
----
base64(expirationTime + ":" + md5Hex(expirationTime + ":" + key))
expirationTime:   nonce가 만료되는 날짜와 시간 (밀리초로 표현)
key:              nonce 토큰의 수정을 방지하기 위한 개인 키
----

안전하지 않은 일반 텍스트 비밀번호 저장을 ``NoOpPasswordEncoder``를 사용하여 구성해야 합니다.
다음은 Java 구성을 사용한 다이제스트 인증 구성의 예시입니다:

.다이제스트 인증
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Autowired
UserDetailsService userDetailsService;

DigestAuthenticationEntryPoint authenticationEntryPoint() {
	DigestAuthenticationEntryPoint result = new DigestAuthenticationEntryPoint();
	result.setRealmName("My App Realm");
	result.setKey("3028472b-da34-4501-bfd8-a355c42bdf92");
	return result;
}

DigestAuthenticationFilter digestAuthenticationFilter() {
	DigestAuthenticationFilter result = new DigestAuthenticationFilter();
	result.setUserDetailsService(userDetailsService);
	result.setAuthenticationEntryPoint(authenticationEntryPoint());
	return result;
}

@Bean
public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
	http
		// ...
		.exceptionHandling(e -> e.authenticationEntryPoint(authenticationEntryPoint()))
		.addFilter(digestAuthenticationFilter());
	return http.build();
}
----

XML::
+
[source,xml,role="secondary"]
----
<b:bean id="digestFilter"
        class="org.springframework.security.web.authentication.www.DigestAuthenticationFilter"
    p:userDetailsService-ref="jdbcDaoImpl"
    p:authenticationEntryPoint-ref="digestEntryPoint"
/>

<b:bean id="digestEntryPoint"
        class="org.springframework.security.web.authentication.www.DigestAuthenticationEntryPoint"
    p:realmName="My App Realm"
	p:key="3028472b-da34-4501-bfd8-a355c42bdf92"
/>

<http>
	<!-- ... -->
	<custom-filter ref="userFilter" position="DIGEST_AUTH_FILTER"/>
</http>
----
======