[[servlet-authentication-userdetailsservice]]
= UserDetailsService

{security-api-url}org/springframework/security/core/userdetails/UserDetailsService.html[`UserDetailsService`]는 xref:servlet/authentication/passwords/dao-authentication-provider.adoc#servlet-authentication-daoauthenticationprovider[`DaoAuthenticationProvider`]에서 사용자 이름과 비밀번호로 인증할 때 사용자 이름, 비밀번호 및 기타 속성을 검색하는 데 사용됩니다.
Spring Security는 ``UserDetailsService``의 xref:servlet/authentication/passwords/in-memory.adoc#servlet-authentication-inmemory[인메모리], xref:servlet/authentication/passwords/jdbc.adoc#servlet-authentication-jdbc[JDBC], 그리고 xref:servlet/authentication/passwords/caching.adoc#servlet-authentication-caching-user-details[캐싱] 구현을 제공합니다.

커스텀 ``UserDetailsService``를 빈으로 노출시켜 사용자 정의 인증을 정의할 수 있습니다.
예를 들어, 다음 코드는 ``CustomUserDetailsService``가 ``UserDetailsService``를 구현한다고 가정하고 인증을 커스터마이즈합니다:

[NOTE]
====
이는 ``AuthenticationManagerBuilder``가 구성되지 않았고 ``AuthenticationProviderBean``이 정의되지 않은 경우에만 사용됩니다.
====

.Custom UserDetailsService Bean
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
CustomUserDetailsService customUserDetailsService() {
	return new CustomUserDetailsService();
}
----

XML::
+
[source,java,role="secondary"]
----
<b:bean class="example.CustomUserDetailsService"/>
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun customUserDetailsService() = CustomUserDetailsService()
----
======